### ISSUE TITLE
Upgrade OmniFaces to 2.5.1

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#187]
Starting from [2.5](http://balusc.omnifaces.org/2016/09/omnifaces-25-released-with-oinputfile.html), [OmniFaces](http://omnifaces.org) 1.1x version is now in maintenance mode. [OmniFaces](http://omnifaces.org) 2.5 requires CDI implementation. JoinFaces uses [OmniFaces](http://omnifaces.org) 1.14.

JoinFaces implements CDI annotations support and Spring supports [jsr-330](https://www.mkyong.com/spring3/spring-3-and-jsr-330-inject-and-named-example/), but it does not mean a full CDI implementation.

How to integrate Spring with CDI implementation?  It could be through Extension: [here](https://www.javacodegeeks.com/2014/02/tutorial-writing-your-own-cdi-extension.html) or [here](https://github.com/CDISource/cdisource/tree/master/spring/src/main/java/org/cdisource/springintegration).
Which CDI implementation should we integrate to JoinFaces?
Could we imagine CDI implementation powered by Spring?

**Comment by persapiens** [comment]
One possibility could be [Seam Spring Module](http://docs.jboss.org/seam/3/spring/latest/reference/en-US/html_single/) that is outdated. It was proposed to become [Spring CDI Integration by DeltaSpike](https://cwiki.apache.org/confluence/display/DeltaSpike/Spring+CDI+integration), which has not been released yet.

Another possibility could be [DS Spring Bridge Addon](https://github.com/os890/ds-spring-bridge-addon) or [this project](https://github.com/os890/jax-rs_cdi_deltaspike_spring-boot_template) from @os890 .

**Comment by BalusC** [comment]
On http://joinfaces.org in its current form I'm seeing 

> Current version includes JSF and CDI annotations support 

So I'm wondering whether the intented OmniFaces 2.x migration as described in this issue is still an issue. If so, what technical difficulties exactly are you facing?

**Comment by persapiens** [comment]
Hi @BalusC , it is my pleasure to talk with you.

One application that uses OmniFaces 2.x requires CDI 1.1 implementation like Weld or OpenWebBeans. 

JoinFaces does **not** implement CDI 1.1. It enables CDI annotations usage like @ViewScoped and @RequestedScoped through custom spring scopes. Actually, beans with these annotations are regular spring beans. They are enabled to JSF through SpringBeanFacesELResolver class.

If we upgrade OmniFaces to 2.x, we must use CDI 1.1 implementation inside spring boot application. So, we will have two "beans containers" (CDI 1.1 implementation and Spring) in the same application. I've read a bit about integrating them, but I don't know the best option.

**Comment by BalusC** [comment]
Okay. I asked this because of http://stackoverflow.com/q/41416546/157882

**Comment by classicPintus** [comment]
Hello,
any news from this topic? Now the released version of omnifaces is 3.0 with a lot of cool implementations.

Making possible to use an embedded TomEE is it a feasible idea?

**Comment by classicPintus** [comment]
Hello guys, seems the integration is working using the information in this answer https://stackoverflow.com/questions/48420941/omnifaces-2-x-fails-when-used-in-a-spring-boot-environment-with-weld/48474573#48474573

**Comment by classicPintus** [comment]
Hi Marcelo,
Nice to meet you.

Yes, I confirm that seems to be working and for me will be a pleasure to help you and joinfaces in general.

I think I'll have enough time in this weekend, and if you allow me to create the starter I'll do that.

Do I need to respect some code conventions? Have you some hints to me?

At the moment I can't use joinfaces in my projects due to some little limitations. But maybe are not limitations, but only my lack of knowledge.
If you can and want we can discuss about that also.

Thank you for contacting me. Very appreciated.

Il 22 feb 2018 01:27, Marcelo Romulo Fernandes <notifications@github.com> ha scritto:

Hi @classicPintus<https://github.com/classicpintus> ,

OmniFaces needs full CDI. Your answer adds Weld to spring boot application. If it works properly, we could create weld-spring-boot-starter to autoconfigure weld.

Would you like creating weld-spring-boot-starter?

Thanks a lot for your information.

I look forward your answer.

**Comment by persapiens** [comment]
Let's go @classicPintus 

- Read and understand [Structure of the Software](https://github.com/joinfaces/joinfaces/wiki/Structure-of-the-software)
- Follow [Creating JoinFaces Starter](https://github.com/joinfaces/joinfaces/wiki/Creating-Spring-Boot-Starter-to-specific-JSF-component-library) to create weld-spring-boot-starter
- JoinFaces codebase follows checkstyle conventions similar to Spring Boot. We also have test coverage check.
- Submit a pull request. We can review frequently before integrating the main branch.

Thanks for your collaboration.
