### ISSUE TITLE
Upgrade Spring Boot to 1.5.4

### ISSUE THREAD

**Issue by mtbadi39** [joinfaces/joinfaces#296]
[Spring Boot 1.5.4 Available Now](https://spring.io/blog/2017/06/08/spring-boot-1-5-4-available-now)

**Comment by persapiens** [comment]
hi @nyilmaz , could you see why ProjectStageAutoConfigurationTest.testProduction fails with spring boot 1.5.4?

I look forward your answer.

**Comment by larsgrefer** [comment]
I'll have a look

**Comment by larsgrefer** [comment]
The problem seems to be a bit complex.

All tests with ```webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT``` are broken with spring boot 1.5.4 because of spring-projects/spring-boot#9095

Tomcat fails to start, because we have 2 JSF implementations on the (test-)classpath:
* https://stackoverflow.com/a/18898156/3574494
* https://stackoverflow.com/a/13014964/3574494

**Comment by larsgrefer** [comment]
I've played around with different solutions and i think the best one is, to use different executions of the failsafe-plugin with different classpath (one for mojarra and one for myfaces).

**Comment by larsgrefer** [comment]
see #298
