### ISSUE TITLE
Extensionless URLs

### ISSUE THREAD

**Issue by wandyer** [joinfaces/joinfaces#323]
I'm using the main starter "jsf-spring-boot-starter" and I want to achieve extensionless URLs without having to map each page to a specific URL.

In JavaEE I would just add 
```
<welcome-file-list>
   <welcome-file>index.xhml</welcome-file>
</welcome-file-list>
```
 in the web.xml and it would serve me index.xhtml in every page if I requested any **_/_** directory. But now I can't find this option for joinfaces inside the application.yml

Basically I want able to access **http://host/foo** or **http://host/bar** and get the corresponding index.xhtml inside the directory.

I tried Omnifaces [ExtensionlessURLs](http://showcase.omnifaces.org/facesviews/ExtensionlessURLs) using this option in joinfaces
`facesViewsScanPaths: /*.xhtml `
as explained in the Omnifaces documentation but it didn't work. I get 404 error when trying to access any page without specifying **index.xhtml**

**Comment by persapiens** [comment]
Hi @wandyer ,

I think you can find your answer in #392

**Comment by larsgrefer** [comment]
Since the _Servlet 3.0 API_ the web.xml can be completely replaced by code, except for the `welcome-file-list` which has no direct counterpart.

So you have the following options:

1. Use `war`-packaging, so you can use a `web.xml` with a `welcome-file-list`-section
2. Use MyFaces' `AUTOMATIC_EXTENSIONLESS_MAPPING` setting which was added with MyFaces 2.3. To use this, set `jsf.myfaces.automatic-extensionless-mapping` to `true`and configure `jsf.faces-servlet.url-mapping` accordingly to also map to the extensionless urls.
3. The Omnifaces feature you mentioned above might be an option if you can get it to work.
4. Since Joinfaces 3.1.0 we have a starter for https://www.ocpsoft.org/rewrite/ which may also help you.

For all the options above, you must be aware if `http://host/foo` maps to `http://host/foo/index.xhtml` or `http://host/foo.xhtml`. While option 1 would map to `foo/index.xhtml`, the extensionless url features mentioned in options 2 and 3 might map to `foo.xhtml` instead. With option 4 you can configure any mapping you want.

**Comment by babltiga** [comment]
If someone needs this functionality with almost 0 configuration following code will do the trick. Still it's kinda ugly but works as expected 😸 

```
public class ExtensionLessConfig implements ServletContextInitializer {

    private static final Logger LOG = LoggerFactory.getLogger(ExtensionLessConfig.class);

    @Override
    public void onStartup(ServletContext servletContext) {
        // Scan our dedicated directory for Faces resources that need to be mapped
        Map<String, String> collectedViews = new HashMap<>();
        scanViewsFromRootPaths(servletContext, collectedViews, null);
        scanJarResources(collectedViews);

        for(String entry : collectedViews.keySet()){
            if(isExtensionless(entry)){
                servletContext.getServletRegistrations().get("FacesServlet").addMapping(entry);
            }
        }
    }

    public static boolean isExtensionless(final String viewId) {
        return viewId != null && !viewId.contains(".");
    }
    
    // this is only needed for jar packaging on IDE this part will be skipped
    private void scanJarResources(Map<String, String> collectedViews){
        PathMatchingResourcePatternResolver loader = new PathMatchingResourcePatternResolver();
        try{
            List<Resource> resources = new ArrayList<>();
            resources.addAll(Arrays.asList(loader.getResources("META-INF/resources/admin/*.xhtml")));
            resources.addAll(Arrays.asList(loader.getResources("META-INF/resources/*.xhtml")));
                for(Resource resource : resources){
                if(resource instanceof ClassPathResource){
                    ClassPathResource classPathResource = (ClassPathResource) resource;
                    String resourcePath = classPathResource.getPath();
                    resourcePath = StringUtils.removeFirst(resourcePath, "META-INF/resources");
                    collectedViews.put(ResourcePaths.stripExtension(resourcePath), resourcePath);
                }
            }
        } catch (IOException ex){
            LOG.error("Error while loading class path resources", ex);
        }
    }
}
```

**Comment by AzharMobeen** [comment]
@wandyer
As per question we can handle this with `WebMvcConfigurer` and can redirect as well as forward.
May be it will help someone:
```
@Configuration
public class CustomWebMvcConfigurer implements WebMvcConfigurer {

    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        //registry.addViewController("/").setViewName("forward:/index.xhtml");
        registry.addViewController("/").setViewName("redirect:/index.xhtml");
        registry.setOrder(Ordered.HIGHEST_PRECEDENCE);
    }
}
```
