### ISSUE TITLE
How to get a FacesContext in a Spring component

### ISSUE THREAD

**Issue by israeldl** [joinfaces/joinfaces#346]
I'm trying to make a mail sender using a jsf xhtml template in a JoinFaces project. The idea is to "render" the jsf and then send the html through email. 

Using OmniFaces this is kind of easy:

> String htmlMail = Components.encodeHtml(Components.buildView("/my-mail-template.jsf"));

But this code just works if I call it through an user interaction (a click in a jsf page). I could not make this work in a simple @Scheduled Spring method, because FacesContext is not available. Is there a way to access the context?

**Comment by persapiens** [comment]
hi @israeldl,

I think this issue is not related to JoinFaces. If you google "create facescontext manually", you will see discussion like [this](https://stackoverflow.com/questions/592496/generating-a-faces-context-manually) or [this](https://stackoverflow.com/questions/22816727/how-to-make-an-instance-of-facescontext).

You could consider using [FreeMarker](https://freemarker.apache.org/) as templating technology to create HTML text.

**Comment by israeldl** [comment]
Hi Marcelo!

You're right! I ended up using FlyingSaucer to access a page and generate a image.

obrigado/thanks!
