### ISSUE TITLE
Adminfaces-starter with war deployment

### ISSUE THREAD

**Issue by Tosken1337** [joinfaces/joinfaces#588]
I am using adminfaces-starter and i followed the instructions in your wwiki to prepare a war deployment for use of an external tomcat.

I am facing a NullPointerException in AdminFilter.class (https://github.com/adminfaces/admin-template/blob/master/src/main/java/com/github/adminfaces/template/session/AdminFilter.java) because AdminConfig could not be injected.

It uses the @Inject annotation which works perfectly when i start the application as jar.

**Comment by persapiens** [comment]
hi @Tosken1337 ,

Are you running your app with `java -jar app.war` or deployed inside servlet container? Which servlet container do you use? Example apps are welcome because they ease debug the issue.

I look forward your answer.

**Comment by persapiens** [comment]
> But when using@webfilter annotation no autowire or inject works and in this case Adminfilter throws NPE because AdminConfig is null

When app is inside Tomcat, it will try to create AdminFilter because of @WebFilter annotation. But Tomcat does not  inject anything. This error will happen with LogoutServlet because of @WebServlet annotation too.

When Tomcat is embedded by Spring Boot, Tomcat does not create AdminFilter and LogoutServlet. They are created by Spring because @ServletComponentScan annotation usage at [AdminfacesAutoConfiguration](https://github.com/joinfaces/joinfaces/blob/a9b00869347f2f02fe2e3ef8307f67bb7f5f3dfa/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/adminfaces/AdminfacesAutoConfiguration.java#L64). In this case, inject works because Spring supports it. However, [@ServletComponentScan](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/web/servlet/ServletComponentScan.html) works only with embedded Servlet Container like Tomcat.

It is possible to change JoinFaces implementation in order to remove @ServletComponentScan usage and to create AdminFilter and LogoutServlet in all cases (embedded and not embedded). But Tomcat will try to create AdminFilter and LogoutServlet too at not embedded environments and you will get NPE anyway.
