### ISSUE TITLE
Slow JSF lifecycle when running as jar/war

### ISSUE THREAD

**Issue by Primi2000** [joinfaces/joinfaces#654]
Hi!

We migrated a big project from Wildfly 12 to Spring Boot 2.1.3 with JoinFaces 4.0.3, Primefaces 6.2.15 and OmniFaces 1.14.1. The server is running with Java 1.8

The problem we are facing is, that the JSF lifecycle rountrips are 10-30 times slower, if we package the project as jar or war, than simply starting it with gradle bootrun. We measured the time using a JSF PhaseListener and the execution time is distributed to all phases, so it's difficult to pinpoint the problem source. Smaller pages with just a few components are not that problematic, but we also have pages with over 1000 components and there we have roundtrip times of up to 1-2 minutes.

Is there a special way how the jar/war archive has to be built/composed/started? Or are there any starters, which cause complications with JoinFaces?

We are thankful for every hint!

**Comment by larsgrefer** [comment]
I've noticed performance differences between repacked archives (jar, war) and other methods while working on #565. I this specific case the performance problem was in the handling/classloading of nested jar files in Spring Boot itself: spring-projects/spring-boot#15096

Your problem might be related to this, so im not sure if it's a JoinFaces problem or a Spring Boot problem.

You can try out other ways to run your application than as repackaged jar:

- Unzip the repackaged jar before starting the application: https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#executable-jar-exploded-archives
- Package the application using the 'application' gradle plugin (make sure to use `installDist`/`distZip` instead of `installBootDist`/`bootDistZip`)
- When building Docker containers you could try [jib](https://github.com/GoogleContainerTools/jib)

**Comment by larsgrefer** [comment]
@Primi2000 Were you able to solve your problems?
