### ISSUE TITLE
joinfaces.faces-servlet.url-mappings - Invalid <url-pattern>

### ISSUE THREAD

**Issue by vitsin** [joinfaces/joinfaces#770]
JoinFaces: v4.1.0-rc1
Issue: set joinfaces.faces-servlet.url-mappings in the application.properties.

Tried:
```properties
joinfaces.faces-servlet.url-mappings="/faces/", ".faces", ".xhtml"
joinfaces.faces-servlet.url-mappings="/faces/, .faces, .xhtml"
joinfaces.faces-servlet.url-mappings=/faces/, .faces, .xhtml
```

Result: same error in all above cases: IllegalArgumentException: Invalid <url-pattern> ["/faces/"] in servlet mapping 

What am I doing wrong ?
thank you

**Comment by larsgrefer** [comment]
The first variant resolves to three mappings: ```"/faces/"```, ```".faces"``` and ```".xhtml"```
These are invalid, because they contain the `"` character.

The second variant resolves to three mappings: ```"/faces/```, ```.faces``` and ```.xhtml"```
The first one of these is invalid, because it starts with `"`

The third variant resolves to three mappings: ```/faces/```, ```.faces``` and ```.xhtml```
The first one of these is vaild, but the second one is invalid, because it starts with a `.`(dot)

I assume you'd want this definition:

```properties
joinfaces.faces-servlet.url-mappings=/faces/*, *.faces, *.xhtml
```

More information about valid url patterns can be found in [Section 12.2 of the Servlet Specification](https://javaee.github.io/servlet-spec/downloads/servlet-4.0/servlet-4_0_FINAL.pdf#G16.999478)

**Comment by vitsin** [comment]
thank you!
