### ISSUE TITLE
Properties joinfaces.rewrite.scan-classpath and joinfaces.rewrite.base-packages don't work

### ISSUE THREAD

**Issue by OLibutzki** [joinfaces/joinfaces#813]
In contrast to the documentation the properties _joinfaces.rewrite.scan-classpath_ and _joinfaces.rewrite.base-package_ are ignored by joinfaces. 

_joinfaces.rewrite.annotationConfigProvider.enabled_ and  _joinfaces.rewrite.annotationConfigProvider.base-packages_ seem to work instead.

**Comment by feverdog** [comment]
I've also had issues with this.

**Comment by larsgrefer** [comment]
The properties 
```
joinfaces.rewrite.base-packages=
joinfaces.rewrite.scan-classes-directory=
joinfaces.rewrite.scan-lib-directory=
```
configure the annotation scanning mechanism integrated into rewrite itself.

Since the built-in mechanism only works for war-packaged applications (deployed to an external servlet container), JoinFaces defaults `joinfaces.rewrite.base-packages=none` (thus disabling the built-in scanning mechanism).
As replacement, JoinFaces provides `org.joinfaces.autoconfigure.rewrite.SpringBootAnnotationConfigProvider` which works for both jar- and war-packaging.

The alternative mechanism provided by JoinFaces can be configured by these properties:

```
joinfaces.rewrite.annotation-config-provider.enabled=true
joinfaces.rewrite.annotation-config-provider.base-packages=
```
