### ISSUE TITLE
Enhancement: implement @WindowScoped from deltaspike

### ISSUE THREAD

**Issue by torstenwerner** [joinfaces/joinfaces#820]
I am trying to port an application to spring that uses many @WindowScoped beans where the scope is bound to the current browser window / tab. It would be nice if joinfaces could implement such a scope. I am willing to help if I am getting some instructions how to start.

**Comment by larsgrefer** [comment]
You'd need to implement Springs `org.springframework.beans.factory.config.Scope` interface.

Joinfaces already contains two of those, which you can use as examples:
- https://github.com/joinfaces/joinfaces/blob/master/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/viewscope/ViewScope.java
- https://github.com/joinfaces/joinfaces/blob/master/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/icefaces/WindowScope.java

Both of these are accompanied by an AutoConfiguration which declare a `org.springframework.beans.factory.config.CustomScopeConfigurer` Bean, which exposes the Scope implementation to the `ApplicationContext`

**Comment by israeldl** [comment]
Hi Lars. I'm very sorry to ask this here (because is not a so related question). There is something limiting the number of view scopes active, right?

I'm looking for a way to create a type of view a little more persistent (I don't want the view to die after the views limit is reached). Maybe implementing this WindowScoped is a way to do this? Or there is a simpler way?
