### ISSUE TITLE
https://joinfaces-example.herokuapp.com/fileUpload.jsf example not working

### ISSUE THREAD

**Issue by aspirations** [joinfaces/joinfaces#886]
@melloware  Can you please check this when even I am downloading it is showing 0KB

**Comment by melloware** [comment]
I will see if I can look into this.

**Comment by melloware** [comment]
@aspirations I think the issue is that if you look at the PrimeFaces Showcase:
https://www.primefaces.org/showcase/ui/file/upload/basic.xhtml?

The bean is `@RequestScoped` and you use the `UploadFile` value and then its done. the JoinFaces example is `@ViewScoped` and marks the bean `transient` but I don't think you can use the `UploadFile` this way.  So I am pretty sure that is the problem.

**Comment by melloware** [comment]
@aspirations this can be closed

**Comment by aspirations** [comment]
Yes you can close. Thank You

**Comment by melloware** [comment]
You opened the ticket I think you are the only one with permission to close it
